Testing for following row: 
Nodes           5
N_Rows          3
N_Iterations    5
Name: 0, dtype: int64
Deleted featurestore 'performance_testing'.
name: "projects/180938242395/locations/us-central1/featurestores/performance_testing"

name: "projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies"
etag: "AMEw9yPFSUoybczUT5RwOHrW9i013iQyVZtvXbobZ7zgA7z91Me0"

Ran for a total of 0:06:33.687768
imported_entity_count: 3
imported_feature_value_count: 105

Ran for a total of: 0.28771543502807617 seconds for 3 streaming predictions 
 Per prediction seconds: 0.09590514500935872
Ran for a total of: 0.16782784461975098 seconds for 3 streaming predictions 
 Per prediction seconds: 0.05594261487325033
Ran for a total of: 0.02015519142150879 seconds for 3 streaming predictions 
 Per prediction seconds: 0.00671839714050293
Ran for a total of: 0.19650673866271973 seconds for 3 streaming predictions 
 Per prediction seconds: 0.06550224622090657
Ran for a total of: 0.16091179847717285 seconds for 3 streaming predictions 
 Per prediction seconds: 0.05363726615905762
Ran for a total of: 0.15851759910583496 seconds for 3 streaming predictions 
 Per prediction seconds: 0.052839199701944985
Ran for a total of: 0.15779733657836914 seconds for 3 streaming predictions 
 Per prediction seconds: 0.05259911219278971
Ran for a total of: 0.02171158790588379 seconds for 3 streaming predictions 
 Per prediction seconds: 0.00723719596862793
Ran for a total of: 0.1604611873626709 seconds for 3 streaming predictions 
 Per prediction seconds: 0.05348706245422363
Ran for a total of: 0.15316057205200195 seconds for 3 streaming predictions 
 Per prediction seconds: 0.051053524017333984
Ran for a total of: 0.02782440185546875 seconds for 3 streaming predictions 
 Per prediction seconds: 0.009274800618489584
Ran for a total of: 0.18972158432006836 seconds for 3 streaming predictions 
 Per prediction seconds: 0.06324052810668945
Ran for a total of: 0.19228506088256836 seconds for 3 streaming predictions 
 Per prediction seconds: 0.06409502029418945
Ran for a total of: 0.16608786582946777 seconds for 3 streaming predictions 
 Per prediction seconds: 0.05536262194315592
Ran for a total of: 0.15548443794250488 seconds for 3 streaming predictions 
 Per prediction seconds: 0.05182814598083496
Ran for a total of: 0.029371023178100586 seconds for 3 streaming predictions 
 Per prediction seconds: 0.009790341059366861
Ran for a total of: 0.02398371696472168 seconds for 3 streaming predictions 
 Per prediction seconds: 0.007994572321573893
Ran for a total of: 0.30011868476867676 seconds for 3 streaming predictions 
 Per prediction seconds: 0.10003956158955891
Ran for a total of: 0.19619035720825195 seconds for 3 streaming predictions 
 Per prediction seconds: 0.06539678573608398
Ran for a total of: 0.18362808227539062 seconds for 3 streaming predictions 
 Per prediction seconds: 0.06120936075846354
Ran for a total of: 0.22800040245056152 seconds for 3 streaming predictions 
 Per prediction seconds: 0.07600013415018718
Ran for a total of: 0.1940772533416748 seconds for 3 streaming predictions 
 Per prediction seconds: 0.06469241778055827
Ran for a total of: 0.14259624481201172 seconds for 3 streaming predictions 
 Per prediction seconds: 0.047532081604003906
Ran for a total of: 0.18161273002624512 seconds for 3 streaming predictions 
 Per prediction seconds: 0.06053757667541504
Ran for a total of: 0.1607823371887207 seconds for 3 streaming predictions 
 Per prediction seconds: 0.053594112396240234
Ran for a total of: 0.17318081855773926 seconds for 3 streaming predictions 
 Per prediction seconds: 0.05772693951924642
Ran for a total of: 0.21083998680114746 seconds for 3 streaming predictions 
 Per prediction seconds: 0.07027999560038249
Ran for a total of: 0.023192405700683594 seconds for 3 streaming predictions 
 Per prediction seconds: 0.007730801900227864
Ran for a total of: 0.16878318786621094 seconds for 3 streaming predictions 
 Per prediction seconds: 0.05626106262207031
Ran for a total of: 0.0272064208984375 seconds for 3 streaming predictions 
 Per prediction seconds: 0.009068806966145834
0.0272064208984375
Traceback (most recent call last):
  File "run_experiment.py", line 100, in <module>
    main()
  File "run_experiment.py", line 91, in main
    append_frame = pd.Dataframe(repeat_run_data, columns=data.columns)
  File "/opt/conda/lib/python3.7/site-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'Dataframe'
Testing for following row: 
Nodes           3
N_Rows          2
N_Iterations    9
Name: 0, dtype: int64
name: "projects/180938242395/locations/us-central1/featurestores/performance_testing"

name: "projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies"
etag: "AMEw9yPRtqC13ezkO3Xm7K0ZFSpl5JIv-MzxHVAsQf8_CCdN0tHf"

Ran for a total of 0:07:10.901057
imported_entity_count: 2
imported_feature_value_count: 126

Ran for a total of: 0.2718474864959717 seconds for 2 streaming predictions 
 Per prediction seconds: 0.13592374324798584
Ran for a total of: 0.1659104824066162 seconds for 2 streaming predictions 
 Per prediction seconds: 0.0829552412033081
Ran for a total of: 0.16928744316101074 seconds for 2 streaming predictions 
 Per prediction seconds: 0.08464372158050537
Ran for a total of: 0.0240023136138916 seconds for 2 streaming predictions 
 Per prediction seconds: 0.0120011568069458
Ran for a total of: 0.207550048828125 seconds for 2 streaming predictions 
 Per prediction seconds: 0.1037750244140625
Ran for a total of: 0.17359375953674316 seconds for 2 streaming predictions 
 Per prediction seconds: 0.08679687976837158
Ran for a total of: 0.20109868049621582 seconds for 2 streaming predictions 
 Per prediction seconds: 0.10054934024810791
Ran for a total of: 0.172210693359375 seconds for 2 streaming predictions 
 Per prediction seconds: 0.0861053466796875
Ran for a total of: 0.20129847526550293 seconds for 2 streaming predictions 
 Per prediction seconds: 0.10064923763275146
Ran for a total of: 0.21490073204040527 seconds for 2 streaming predictions 
 Per prediction seconds: 0.10745036602020264
Ran for a total of: 0.022150278091430664 seconds for 2 streaming predictions 
 Per prediction seconds: 0.011075139045715332
Ran for a total of: 0.21214580535888672 seconds for 2 streaming predictions 
 Per prediction seconds: 0.10607290267944336
Ran for a total of: 0.1699988842010498 seconds for 2 streaming predictions 
 Per prediction seconds: 0.0849994421005249
Ran for a total of: 0.026471853256225586 seconds for 2 streaming predictions 
 Per prediction seconds: 0.013235926628112793
Ran for a total of: 0.17323899269104004 seconds for 2 streaming predictions 
 Per prediction seconds: 0.08661949634552002
Ran for a total of: 0.1846904754638672 seconds for 2 streaming predictions 
 Per prediction seconds: 0.0923452377319336
Ran for a total of: 0.20041608810424805 seconds for 2 streaming predictions 
 Per prediction seconds: 0.10020804405212402
Ran for a total of: 0.024715185165405273 seconds for 2 streaming predictions 
 Per prediction seconds: 0.012357592582702637
Ran for a total of: 0.023344993591308594 seconds for 2 streaming predictions 
 Per prediction seconds: 0.011672496795654297
Ran for a total of: 0.15569710731506348 seconds for 2 streaming predictions 
 Per prediction seconds: 0.07784855365753174
Ran for a total of: 0.16677427291870117 seconds for 2 streaming predictions 
 Per prediction seconds: 0.08338713645935059
Ran for a total of: 0.17876505851745605 seconds for 2 streaming predictions 
 Per prediction seconds: 0.08938252925872803
Ran for a total of: 0.19288182258605957 seconds for 2 streaming predictions 
 Per prediction seconds: 0.09644091129302979
Ran for a total of: 0.19289422035217285 seconds for 2 streaming predictions 
 Per prediction seconds: 0.09644711017608643
Ran for a total of: 0.1645970344543457 seconds for 2 streaming predictions 
 Per prediction seconds: 0.08229851722717285
Ran for a total of: 0.18832612037658691 seconds for 2 streaming predictions 
 Per prediction seconds: 0.09416306018829346
Ran for a total of: 0.16219830513000488 seconds for 2 streaming predictions 
 Per prediction seconds: 0.08109915256500244
Ran for a total of: 0.015149831771850586 seconds for 2 streaming predictions 
 Per prediction seconds: 0.007574915885925293
Ran for a total of: 0.18010902404785156 seconds for 2 streaming predictions 
 Per prediction seconds: 0.09005451202392578
Ran for a total of: 0.02364516258239746 seconds for 2 streaming predictions 
 Per prediction seconds: 0.01182258129119873
0.02364516258239746
Traceback (most recent call last):
  File "run_experiment.py", line 100, in <module>
    main()
  File "run_experiment.py", line 91, in main
    append_frame = pd.DataFrame(repeat_run_data, columns=data.columns)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 422, in dict_to_mgr
    index = _extract_index(arrays[~missing])
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
Testing for following row: 
Nodes           6
N_Rows          2
N_Iterations    9
Name: 0, dtype: int64
Deleted featurestore 'performance_testing'.
name: "projects/180938242395/locations/us-central1/featurestores/performance_testing"

name: "projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies"
etag: "AMEw9yPY8qc-TXC2ZpmX82te2dMvqpirVYxa9Pb9Gzu_tlbwyuhb"

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Operation projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies/operations/1392418364319596544 not found."
	debug_error_string = "{"created":"@1634829007.358961915","description":"Error received from peer ipv4:142.250.125.95:443","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Operation projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies/operations/1392418364319596544 not found.","grpc_status":5}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_experiment.py", line 100, in <module>
    main()
  File "run_experiment.py", line 90, in main
    , row['Nodes'], n_repeats=30)
  File "run_experiment.py", line 46, in repeat_measure
    stats = create_a_fs_run(n_iterations, n_predictions, n_workers)
  File "/home/jupyter/matching-engine-demo/Feature_Store_Examples/helper_fns/helpers.py", line 260, in create_a_fs_run
    poll_loading_data(ingestion_lro)
  File "/home/jupyter/matching-engine-demo/Feature_Store_Examples/helper_fns/helpers.py", line 207, in poll_loading_data
    if ingestion_lro.done():
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/operation.py", line 170, in done
    self._refresh_and_update(retry)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/operation.py", line 158, in _refresh_and_update
    self._operation = self._refresh(retry=retry)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/operations_v1/operations_client.py", line 143, in get_operation
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.NotFound: 404 Operation projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies/operations/1392418364319596544 not found.
Testing for following row: 
Nodes           4
N_Rows          9
N_Iterations    8
Name: 0, dtype: int64
name: "projects/180938242395/locations/us-central1/featurestores/performance_testing"

name: "projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies"
etag: "AMEw9yMGZetA-g21t-qAvtyESV7RyP7Bt2acwsWeU2Hh4bzXgLC2"

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Quota exceeded for quota metric 'Resource management (CRUD) requests' and limit 'Resource management (CRUD) requests per minute per region' of service 'aiplatform.googleapis.com' for consumer 'project_number:180938242395'."
	debug_error_string = "{"created":"@1634832123.455197408","description":"Error received from peer ipv4:172.217.212.95:443","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Quota exceeded for quota metric 'Resource management (CRUD) requests' and limit 'Resource management (CRUD) requests per minute per region' of service 'aiplatform.googleapis.com' for consumer 'project_number:180938242395'.","grpc_status":8}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ResourceExhausted: 429 Quota exceeded for quota metric 'Resource management (CRUD) requests' and limit 'Resource management (CRUD) requests per minute per region' of service 'aiplatform.googleapis.com' for consumer 'project_number:180938242395'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_experiment.py", line 98, in <module>
    main()
  File "run_experiment.py", line 86, in main
    , row['Nodes'], n_repeats=30)
  File "run_experiment.py", line 47, in repeat_measure
    stats = create_a_fs_run(n_iterations, n_predictions, n_workers)
  File "/home/jupyter/matching-engine-demo/Feature_Store_Examples/helper_fns/helpers.py", line 260, in create_a_fs_run
    poll_loading_data(ingestion_lro)
  File "/home/jupyter/matching-engine-demo/Feature_Store_Examples/helper_fns/helpers.py", line 207, in poll_loading_data
    if ingestion_lro.done():
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/operation.py", line 170, in done
    self._refresh_and_update(retry)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/operation.py", line 158, in _refresh_and_update
    self._operation = self._refresh(retry=retry)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/operations_v1/operations_client.py", line 143, in get_operation
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/retry.py", line 211, in retry_target
    last_exc,
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x7fbf5aadb8c0>, name: "projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies/operations/3733058717529145344"
, metadata=[('x-goog-request-params', 'name=projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies/operations/3733058717529145344'), ('x-goog-api-client', 'gl-python/3.7.10 grpc/1.38.1 gax/1.31.2')]), last exception: 429 Quota exceeded for quota metric 'Resource management (CRUD) requests' and limit 'Resource management (CRUD) requests per minute per region' of service 'aiplatform.googleapis.com' for consumer 'project_number:180938242395'.
Testing for following row: 
Nodes           4
N_Rows          5
N_Iterations    3
Name: 0, dtype: int64
Deleted featurestore 'performance_testing'.
name: "projects/180938242395/locations/us-central1/featurestores/performance_testing"

name: "projects/180938242395/locations/us-central1/featurestores/performance_testing/entityTypes/movies"

Ran for a total of 0:05:36.244278
imported_entity_count: 5
imported_feature_value_count: 105

Ran for a total of: 0.25365495681762695 seconds for 5 streaming predictions 
 Per prediction seconds: 0.05073099136352539
Traceback (most recent call last):
  File "run_experiment.py", line 100, in <module>
    main()
  File "run_experiment.py", line 88, in main
    , row['Nodes'], n_repeats=30)
  File "run_experiment.py", line 52, in repeat_measure
    data['create_stats'].append(stats)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/series.py", line 2878, in append
    to_concat, ignore_index=ignore_index, verify_integrity=verify_integrity
  File "/opt/conda/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'float'>'; only Series and DataFrame objs are valid
